# .github/workflows/main.yml

name: Trigger Netlify
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Build Hook
        run: curl -s -X POST https://api.netlify.com/build_hooks/5fd4f45c6e0e2ef010090974
